### ISSUE TITLE
support for std::list

### ISSUE THREAD

**Issue by DingXuefeng** [scikit-hep/uproot5#1017]
Currently our collaboration keeps part of data in a TTree holding CalibEvent class type objects. The CalibEvent class holds its member in std::list<CalibChannel>, and std::list is not parsed by uproot5. It is not easy to update the software from our side since it's used by many packages. 

If uproot5 can add support for std::list it would be nice. If there is not enough manpower I'd like to help, and some hints would be very useful where to start.

**Comment by jpivarski** [comment]
I'm willing to help you implement that. The first step is to get a file with a `std::list` in it, preferably a small file, a simple file, or a file for which the values in the list are known. The process of looking at the bytes and recognizing how a `std::list` is to be interpreted will be much easier if you can recognize the values in the list as bytes. Thus, it's easier if the values in the list are integers smaller than 256 or floating point numbers that are powers of 2—those are much easier to recognize by eye.

The next step will likely be in uproot/interpretation/identify.py, to recognize `std::list` in the C++ type string. It would likely be very similar to `std::vector`, so probably just another stanza after this one:

https://github.com/scikit-hep/uproot5/blob/ccb56b25e44ac94e26da1cabcda172854118ce9e/src/uproot/interpretation/identify.py#L958-L971

In the above, you can see that we use `uproot.containers.AsVector` to represent the `std::vector` interpretation. This is in uproot/containers.py. This file defines both `AsVector` the interpretation of the _type_ and `STLVector` the instantiation of a _value_ if not Awkward Array (e.g. if read with `library="np"`). Here is the definition of `AsVector`:

https://github.com/scikit-hep/uproot5/blob/ccb56b25e44ac94e26da1cabcda172854118ce9e/src/uproot/containers.py#L1009-L1209

and here is `STLVector`:

https://github.com/scikit-hep/uproot5/blob/ccb56b25e44ac94e26da1cabcda172854118ce9e/src/uproot/containers.py#L1729-L1782

The `STLVector` is very straightforward; just a class with `__getitem__` and `__iter__` and such, so that it acts like a Sequence in Python. The `AsVector` is more complex because it's handling several cases:

* Content as a value type, like `int32` or `float64`, versus content as a more complex kind of record.
* Reading the data from an entry of a TTree versus reading the data as an object that has been saved directly in a TDirectory.
* Filling an Awkward Array (only TTree with `library="ak"` or `library="pd"` through [awkward-pandas](https://github.com/intake/awkward-pandas)) versus filling a `STLVector`.
* Using AwkwardForth if it is available (subset of Awkward case).
* Reading memberwise or non-memberwise data (only non-memberwise has been implemented, but the other case needs to raise an error).

The first question I should have asked you is whether your `std::list` and `CalibEvent` are inside of a TTree or on their own in a TDirectory, since that cuts out some of the cases.

Even if it is inside of a TTree, which has more subcases, there is a minimal implementation that you can do to avoid the complex cases:

* Do implement the value type versus complex record, even if you only have one kind of data, because this switch doesn't add much complexity and it would be confusing to future users if it handles `std::list` for one type of content but not another.
* The things you need to worry about for inside-of-TTree are a strict superset of outside-of-TTree, so if your data are in a TTree, we'll get the outside-of-TTree case for free.
* Don't worry about special-casing for Awkward Arrays or AwkwardForth. AwkwardForth is especially complicated and is being deeply refactored right now (#943), so it would not pay to solve that problem in the `main` branch. You can do

```python
if forth_stash is not None:
    context["cancel_forth"] = True
```

* We have not been implementing memberwise deserialization anywhere, except in `std::map`, for which our only examples are memberwise (so for that one, we don't implement non-memberwise). You can check for memberwise (or non-memberwise, whichever your case isn't) and raise an error for the unhandled case.

As test-driven development, you can stub the `read_members` method of `AsList` with `cursor.debug(chunk)` ([docs](https://uproot.readthedocs.io/en/latest/uproot.source.cursor.Cursor.html#debug)) followed by an exception just to stop the program flow. The debugging output looks like

```
--+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+-
123 123 123  63 140 204 205  64  12 204 205  64  83  51  51  64 140 204 205  64
  {   {   {   ? --- --- ---   @ --- --- ---   @   S   3   3   @ --- --- ---   @
                        1.1             2.2             3.3             4.4
    --+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+-
    176   0   0  64 211  51  51  64 246 102 102  65  12 204 205  65  30 102 102  66
    --- --- ---   @ ---   3   3   @ ---   f   f   A --- --- ---   A ---   f   f   B
            5.5             6.6             7.7             8.8             9.9
    --+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+-
    202   0   0  67  74   0   0  67 151 128   0 123 123
    --- --- ---   C   J --- ---   C --- --- ---   {   {
          101.0           202.0           303.0
```

(with some of the options turned on, `dtype=">f4"` and `offset=3`). The three rows that are always present are the `--+---+---+---+---` separators, the decimal-valued bytes, and the interpretation as printable characters. With a given `dtype`, the debugging output will also show you the values interpreted as a numeric type, but you have to get the `offset` correct for this to be useful. Since not all of the data belong to a given `dtype`, it's usually easier to put data in the file that correspond to easy-to-read bytes. For example, big-endian (ROOT is big-endian) int32 values look like this as bytes:

```python
>>> np.array([1, 2, 3, 4, 5], dtype=">i4").view("u1")
array([0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5],
      dtype=uint8)
```

That's very readable, even if it's embedded among some headers and strings. (Strings are easy to identify from the character interpretation lines.) Keep in mind that you want the numbers you're using as anchors to be distinguishable from the surrounding headers, which often have a lot of zeros, so pick numbers that are not zero (or one). `123` is a great one to use; it's easy to pick out by eye and it's small enough to fit in one byte.

After having said all of that, I _highly suspect_ that the byte-serialization of `std::list` will be just like that of `std::vector`. I _highly suspect_ that there will be a 6 byte header that you can ignore, but it will start with a decimal `64` (that's a high-bit flag in a 4-byte integer part of the 6 byte header), followed by a 4 byte "number of items in the `std::list`," followed by that many data values.

For example:

```
--+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+-
 64   0   0  22   0   3   0   0   0   5   0   0   0   1   0   0   0   2   0   0
  @ --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+-
  0   3   0   0   0   4   0   0   0   5
--- --- --- --- --- --- --- --- --- ---
```

where the total number of bytes in the object (which you don't need) is 22, the `std::list` serialization version (that I just made up) is 3, there are 5 elements in the list, followed by the values for 1, 2, 3, 4, and 5.


That's a guess, but the reason I guessed that is because it's how `std::vector` is serialized, how `std::set` is serialized, how `std::map` would be serialized except that it's memberwise and the data come in key-value pairs, and it's how ROOT's `RVec` is serialized. I'd be surprised if they break pattern for `std::list`. (How these STL objects are implemented in memory in C++ doesn't matter for how they are serialized to disk.)

Good luck, and I'm available for help if you have any questions!
