### ISSUE TITLE
Use cramjam to provide compression utilities

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot5#1089]
@lgray mentioned https://pypi.org/project/cramjam/ to me and it looks like a nice solution to provide many of the ROOT compression algorithms in a single dependency-free package. Additionally, it allows to declare the output length so it can pre-allocate the buffer, which may provide some speedup for algorithms other than lz4, which is the only one currently using the uncompressed size hint:
https://github.com/scikit-hep/uproot5/blob/fd0637bf978d75619e125a7f624827348f757865/src/uproot/compression.py#L194

This is an internal feature and would not provide any user enhancement other than a potential speed-up

**Comment by lgray** [comment]
Just to finish the chain this was mentioned to me by @martindurant.

**Comment by martindurant** [comment]
> it allows to declare the output length so it can pre-allocate the buffer

You can also allocate buffers yourself and decompress_into - I don't know if there's a use case for that.

**Comment by nsmith-** [comment]
Actually, yes! One thing uproot is often doing is decompressing many small chunks and then concatenating them into a larger contiguous buffer. We could save some additional allocation and copy time if we can decompress into a buffer at an arbitrary offset.

**Comment by martindurant** [comment]
> if we can decompress into a buffer at an arbitrary offset.

yes, certainly you can, I think by just slicing the base numpy array

**Comment by jpivarski** [comment]
Since we want Uproot to work in Pyodide, it's important to note that [cramjam works in Pyodide](https://github.com/pyodide/pyodide/tree/main/packages/cramjam).

![image](https://github.com/scikit-hep/uproot5/assets/1852447/df38ff41-df74-4d90-9e8a-d61114549223)

Writing into a single, contiguous buffer with `decompress_into` would require some rearchitecting—possible, but a major project. Also, it could only work for non-ragged data (or only the outer indexes of ragged data). It could perhaps be an extension of [uproot.AsDtypeInPlace](https://uproot.readthedocs.io/en/latest/uproot.interpretation.numerical.AsDtypeInPlace.html).

**Comment by jpivarski** [comment]
I've split out the request to use cramjam's decompress-in-place into a new issue; this will be closed when #1090 is.
