### ISSUE TITLE
Serialization for number of histogram entries

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot5#1276]
When creating a histogram with ROOT and serializing it with `uproot`, the `GetEntries()` (number of times it has been filled) count does not seem to get serialized correctly:

```python
import ROOT
import uproot

h = ROOT.TH1D('h', 'h', 10, 0, 1)
h.Sumw2()
h.Fill(0.2, 0.1)
h.Fill(0.4, 0.5)
assert h.GetEntries() == 2.0

# save with uproot, load with ROOT
with uproot.recreate("tmp.root") as f:
    f["h"] = h

g = ROOT.TFile.Open("tmp.root")
print(g["h"].GetEntries())  # this is 0.6 now, but should be 2
```

This was tested with `uproot` 5.3.10.

I originally ran into this when testing the serialization of `hist` histograms instead:
```python
import hist

h = hist.Hist.new.Reg(10, 0, 1).Weight()
h.fill([0.2, 0.4], weight=[0.1, 0.5])
```

For this setup, the `GetEntries()` (after saving with `uproot` and loading with ROOT) similarly ends up being `0.6` but I am not sure if boost-histogram has this kind of property in the first place.

**Comment by ariostas** [comment]
@alexander-held what version of ROOT are you using? I tried to reproduce it, but it's just printing `2.0` as expected.

**Comment by ariostas** [comment]
I'd say this is just a difference between how ROOT and hist/boost-histogram work. ROOT keeps track of the number of unweighted entries, but boost-histogram doesn't unless it is of `MEAN` type (as far as I can tell).

Uproot is writing the ROOT histogram properly (in all tests I ran) and it is saving all the data it can from boost-histogram histograms. But maybe a clarifying comment could be used here, since it doesn't match for weighted histograms.
https://github.com/scikit-hep/uproot5/blob/d7d9d30180df45061311dd7c65008e3945db967c/src/uproot/writing/identify.py#L327-L328

**Comment by jpivarski** [comment]
That's right: ROOT histograms have separate fields for unbinned entries, mean, and standard deviation, while boost-histograms do not. Starting from a binned boost-histogram, the best we can do is sum over the binned values, which is not exact.

If I'm missing something, ask to reopen the issue and I will.

**Comment by alexander-held** [comment]
Thanks, that helps understand the behavior. I am wondering if `fEntries` has a sensible default value that could be used to convey that it is unknown. A user receiving a `.root` file and not knowing about this could misinterpret the value: they would have to know if the histogram was created with ROOT or boost-histogram to know whether the value can be trusted.
