### ISSUE TITLE
iteration blocks on exception from callback in XRootDResource

### ISSUE THREAD

**Issue by btovar** [scikit-hep/uproot5#456]
When the callback() in XRootDResource.callbacker has an exception, then an iteration never returns.  We found out this by getting socket timeout errors from xrootd.

The simplest way I found to reproduce this is to change the callback [here](https://github.com/scikit-hep/uproot4/blob/03cb08ccb1f47ce0b082117f41a112af1ab403ee/src/uproot/source/xrootd.py#L232) to immediately "raise" an exception, as:

```python
        def callback(status, response, hosts):
            self._xrd_error(status)
            ...rest of code
```
and use this example:

```python
import uproot

source='root://eospublic.cern.ch//eos/opendata/lhcb/AntimatterMatters2017/data/B2HHH_MagnetDown.root'
for a in uproot.behaviors.TBranch.iterate(source, 'H3_isMuon'):
    print(a)

print("not printed if callback fails")
```

When there is an exception, it is printed to the console, but the script never finishes. 

This was tested with uproot 4.1.3 from a pip install.

**Comment by jpivarski** [comment]
I was about to say that we'd need a reproducible test, but I guess we could add an intentional Exception to the callback, at least for a manual test. I don't know how we could do that in CI, but at least for coming up with a solution.

The HTTP Source passes exceptions on to the main thread. The same kind of thing should be possible here.

**Comment by ioanaif** [comment]
From https://github.com/scikit-hep/uproot5/pull/480 it looks like this has been fixed and tested locally as it would be hard to catch this in the CI.
