### ISSUE TITLE
classname_of gives Exception when used on TBranch

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/uproot5#542]
Please consider the following source code

```python
import uproot
import numpy as np


with uproot.recreate("test.root") as f:
    f["Tree"] = {"x": np.array([1,2,3,4,5])}

f = uproot.open("test.root")
print(f.classname_of("Tree/x"))
```

I would expect it to print "TBranch". However, it actually raises an exception: `AttributeError: 'Model_TTree_v20' object has no attribute 'key'`.

Uproot version: 4.1.9

**Comment by jpivarski** [comment]
I hadn't thought of this as a potential use, but since "`/`" hides the distinction between paths into nested directories and paths into nested branches, it makes sense that one would try passing such a path into `classname_of`, `streamer_of`, `class_of`, `title_of`, etc.

The difficulty is that the path-handling is a specialized implementation in [uproot.ReadOnlyDirectory.key](https://uproot.readthedocs.io/en/latest/uproot.reading.ReadOnlyDirectory.html#key)

https://github.com/scikit-hep/uproot4/blob/3fe33aff6d6ed88203eed90f4edb5f2bc720f3e6/src/uproot/reading.py#L2006-L2021

which would have to get generalized out to be able to use them in the other functions that take paths.

Or maybe it just means that [uproot.TBranch.HasBranches](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.HasBranches.html) objects (i.e. TTree and all TBranch classes) should have a `key` method? (What about TBranches that contain TBranches? Would that work? I'm talking to myself...) Such a method can't return an [uproot.reading.ReadOnlyKey](https://uproot.readthedocs.io/en/latest/uproot.reading.ReadOnlyKey.html) because TTrees and TBranches don't have them the way that [uproot.ReadOnlyDirectory](https://uproot.readthedocs.io/en/latest/uproot.reading.ReadOnlyDirectory.html) does, but maybe a mocked "FakeKey" could duck-type to supply the appropriate information...

**Comment by jpivarski** [comment]
This feature request is still open, but I'm not going to attempt to get it in before the 5.0.0 release (next Monday). I'm just removing that label.
