### ISSUE TITLE
[FR] Support non-numpy array in writing

### ISSUE THREAD

**Issue by Moelf** [scikit-hep/uproot5#695]
```python
In [1]: import uproot as up

In [2]: file = up.recreate("example.root")

In [3]: file["hist"] = [1,2,3], [0.1, 0.2, 0.3, 0.4]
# or
In [5]: import array

In [6]: file["hist"] = array.array('i', [1,2,3]), array.array('d', [0.1, 0.2, 0.3, 0.4])
```

both end up with long error saying
```python
-> 1463             uproot.writing.identify.add_to_directory(v, name, directory, streamers)
   1464 
   1465         self._file._cascading.streamers.update_streamers(self._file.sink, streamers)

/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/uproot/writing/identify.py in add_to_directory(obj, name, directory, streamers)
    147 
    148     else:
--> 149         writable = to_writable(obj)
    150 
    151         for rawstreamer in writable.class_rawstreamers:

/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/uproot/writing/identify.py in to_writable(obj)
    630 
    631     else:
--> 632         raise TypeError(
    633             "unrecognized type cannot be written to a ROOT file: " + type(obj).__name__
    634         )

TypeError: unrecognized type cannot be written to a ROOT file: tuple
```

it feels like we can be a bit smarter about this.

**Comment by agoose77** [comment]
It's this section that would need modifying to consider other array formats:
https://github.com/scikit-hep/uproot5/blob/92e91f31976127ab5418abba95380ccc31ad4d8a/src/uproot/writing/identify.py#L192-L203

**Comment by agoose77** [comment]
@jpivarski and I discussed this in a meeting, and concluded that this feature request is probably out of scope for uproot.

The tuple interface for writing hists is used to support numpy histograms (which return the counts and edges as a tuple). Extending this to support non-Numpy arrays is therefore not a goal, rather the user would be encouraged to load their data with Numpy (which is a dependency of uproot to begin with), or use something like `hist` / `boost-histogram`.

Thanks for the FR Jerry!

**Comment by Moelf** [comment]
it just appears to be weird that:
```python
a = mytree.arrays() #say this is an ak array
with up.recreate("blah.root") as file:
    file["newtree"] = a
```
doesn't work

**Comment by jpivarski** [comment]
To provide a little more context, the primary, supported interface for putting histograms in a file is for the right-hand-side to be an instance of a recognized histogram library, such as boost-histogram or hist. (Earlier, I included physt in that, but the field of histogram libraries in Python has narrowed, at least in HEP.) This is the forward-looking way to do things, since adding more metadata or data (such as `fSumw2`) is something we can do indefinitely with named types like `hist.Hist`.

The concession of accepting a tuple of arrays is because this is what `np.histogram` returns, and it's been doing so for long enough that Matplotlib and probably others (including `hist.numpy.histogram`...) also return. It's a convention, rather than a named type, but widely recognized and

```python
with up.recreate("blah.root") as file:
    file["newtree"] = np.histogram(...)
```

is a convenient thing to do, so we'll play along.

However, it's not a convention we invented, we don't have control over it, and therefore we can't extend it. We can't extend it to include the equivalent of `fSumw2` because `np.histogram` would not give us that data. After a user provides `weights=` to `np.histogram` and it returns a 2-tuple, knowledge about the weights is gone. Circumventing it, like

```python
with up.recreate("blah.root") as file:
    file["newtree"] = np.histogram(..., weights=my_weights) + (weights_to_sumw2(..., my_weights),)
```

is no longer convenient. Instead of implementing that `weights_to_sumw2`, which is inconvenient to use and has to agree in binning with `np.histogram`, we should just use a histogram library. (Also, the particular extension above wouldn't work because `np.histogramdd` returns a 3-tuple for 2D histograms.)

Another way to extend NumPy's convention is to allow non-NumPy arrays, such as `array.array` or Awkward Arrays. I don't think it makes much sense to do this, either, because the widely accepted convention takes a tuple of NumPy arrays: NumPy, Matplotlib, and hist.numpy all return tuples of `np.ndarray`. Python's builtin `array.array` is too infrequently used to be relevant, and I'd be very surprised if anything returns histogram contents and edges as Awkward Arrays.

One possible exception: I just noticed that CuPy's `cp.histogram` returns CuPy arrays:

```python
>>> import cupy as cp
>>> bin_contents, bin_edges = cp.histogram(cp.array([1, 2, 3, 4, 5.5]))
>>> type(bin_contents), type(bin_edges)
(cupy._core.core.ndarray, cupy._core.core.ndarray)
```

so maybe this one should be recognized. But it's a short list. Okay, also PyTorch:

```python
>>> import torch
>>> bin_contents, bin_edges = torch.histogram(torch.tensor([1, 2, 3, 4, 5.5]))
>>> type(bin_contents), type(bin_edges)
(torch.Tensor, torch.Tensor)
```

These have special types because they support GPUs (probably also TensorFlow and JAX).

But if we do recognize arrays from these libraries, we can do it by checking

```python
hasattr(array_like, "dtype") and hasattr(array_like, "shape")
```

which includes all of the NumPy array-like libraries, which we can call `np.asarray(array_like)` on, and it does not include Python's `array.array` or Awkward Arrays.

**Comment by agoose77** [comment]
> However, it's not a convention we invented, we don't have control over it, and therefore we can't extend it. 

Just a small note, we _can_ extend it - we don't require that anyone else support our extension, but it starts to place more importance on this unstructured interface than we'd ideally want.

**Comment by jpivarski** [comment]
I meant "can" in a socially responsible sense.  `:)`

**Comment by Moelf** [comment]
sorry, again, I'm not talking about putting histogram into WritableDirectory anymore sorry for the confusion.

The original post used histogram as example and I regret that because it's somewhat a special case.

The real-world problem that triggered this [FR] was that I was trying to clean-up a "corrupted" .root files (one with un-finished TBasket in the middle of the file), and I realized I can't just:
```python
newfile["mytree"] = oldfile["mytree"].arrays()
```
