### ISSUE TITLE
Warn about name conflict between aliases and TBranch names

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot5#775]
I am using uproot 4.3.7

```python
>>> import uproot
>>> uproot.__version__
```

I'm using PI (3.1415...) in my expressions, but in some cases it works, other is not

I am using this file (I hope the link works since I have some problems)

```python
fn = "https://cernbox.cern.ch/s/nrNUJTfBLHltfDy:analysis"
```

This is working

``` python
uproot.concatenate([fn], ["phiModCalo"], 
aliases={"phiModCalo": "where(abs(el_cl_eta) <= 1.425, abs(el_cl_phiCalo) % (PI / 512), abs(el_cl_phiCalo) % (PI / 384))"}, library='pd')

```

This is not working
```python
 uproot.concatenate([fn], [ 'DeltaPhiTG3'],
 aliases={'DeltaPhiTG3': 'abs(2.0 * PI + el_cl_phi) % (PI / 32.0) - PI / 64.0'}, library='pd')
```

In both I am using `PI`, but I have no idea why the second is failing.

```
KeyInFileError: not found: 'PI'
in file /home/turra/cernbox/user.turra.900333.PG_single_electron_egammaET.MVACalib_el_offline.e8453_s3873_r13830_v2_ANALYSIS.root/user.turra.30650965._000001.ANALYSIS.root
in object /analysis;1
```

adding `{'PI': 3.1415}` to the aliases makes both working, but I not sure why one is working... the only difference is the usage of `where`. Is this triggering anything?

**Comment by jpivarski** [comment]
The language used in [aliases](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TTree.TTree.html#aliases) is by default [Python](https://uproot.readthedocs.io/en/latest/uproot.language.python.PythonLanguage.html), and currently that's also the only option. (To use TTreeFormula, we would need some fixes to the long-dormant [formulate](https://github.com/scikit-hep/formulate) package.) It looks like you know that because you're using the `where` function, which is part of NumPy's namespace, but not TTreeFormula.

The Python `scope` when computing this expression

https://github.com/scikit-hep/uproot5/blob/ec80b88737055679ef86957d4ac61fab00ce682a/src/uproot/language/python.py#L429

does not include $\pi$, nor is it one of the functions we inject into this `scope`:

https://github.com/scikit-hep/uproot5/blob/ec80b88737055679ef86957d4ac61fab00ce682a/src/uproot/language/python.py#L257-L318

And, anyway, you wouldn't want it to be a function: `PI()`.

So it looks like there is no $\pi$ in this execution environment nor has there ever been one. The one example that appears to work is... probably?... a TTree with a TBranch named "PI".

So, _should_ we have a $\pi$ in this language/scope? And what should it be named? And what about Euler's constant, $e$?

* Python adopts C/C++ convention for constants, so maybe it ought to be `PI` and `E`, except that $\pi$ is `np.pi` and `math.pi` and all the other functions follow NumPy naming conventions (except that both `asin` and `arcsin` are provided; different languages disagree on whether the whole word "arc" is needed). So maybe they should be lowercase, like `pi` and `e`?
* A single-letter constant like `E` or `e` is pretty dangerous. In many physics contexts, a single-letter "e" would represent energy. Presumably, TTree branch names should take precedence over named constants, but there would be a danger of someone thinking they have an `E` or `e` TBranch, but get Euler's constant instead.
* NumPy and Python's math module don't have Euler's constant because it's easy enough to say `exp(1)`.
* By the same token, couldn't you say `2*asin(1)` for $\pi$? I suppose, but it would make the formulas unclear.
* You know, in your [arrays](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.HasBranches.html#uproot-behaviors-tbranch-hasbranches-arrays), [iterate](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.HasBranches.html#uproot-behaviors-tbranch-hasbranches-iterate), [uproot.iterate](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.iterate.html), or [uproot.concatenate](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.concatenate.html) function call, you could pass `aliases={"PI": "2*asin(1)"}` to add a new alias, which is used with the others. The others may be embedded in the file or passed explicitly: what gets computed is the union of both TTree's `fAliases` and explicit `aliases`. I think there's also no order dependence to the declarations and references of those functions (because that enables self-reference, for defining recursive functions).

What about that last suggestion: define your own `PI`? I could convert this Issue into a Discussion and this would become a recommendation, rather than a change to the code. The good thing about define-your-own-`PI` is that you can't be surprised about its presence or absence, unless you happen to have a TTree branch named "PI".

**Comment by wiso** [comment]
I found the issue. I have a branch called `phiModCalo` in the tree. So it seems that the alias `""phiModCalo": "..."` is ignored. Maybe a warning in this case?

**Comment by jpivarski** [comment]
So the branch named "phiModCalo" took precedence over the alias defined with name "phiModCalo". I think it would be fine to raise an error in case of conflict, or maybe a warning because I'm thinking about cases where that behavior would be desired.

But is it really the case that when this happened, the error message was

```
KeyInFileError: not found: 'PI'
```

? Because an error message that bad is a bug.

**Comment by jpivarski** [comment]
Oh, wait a minute! It was that `PI` is not defined in either case, but the alias is ignored when it's overshadowed by a TBranch name, right? You were seeing the

```
KeyInFileError: not found: 'PI'
```

error when it attempted to compute `DeltaPhiTG3`, but it never attempted to compute `phiModCalo` because that's a TBranch name.

In which case, we can't fix that error, but we can add a warning when an alias name conflicts with a TBranch name.

**Comment by wiso** [comment]
Than you @jpivarski.
As you said, if the alias is trying to redefine an existing branch it has no effect, even if it contains an undefined symbol. And I don't have any error/warning.
If the alias is trying to define a new variable (not already existing) and it contains an undefined symbol (PI) it raises an error.

The behaviour is correct. We are talking about adding a warning in case the user tries to define an alias with the same name as a branch. Let discuss this in the MR.
