### ISSUE TITLE
scikit-hep/uproot still gets forwarded to uproot3

### ISSUE THREAD

**Issue by ast0815** [scikit-hep/uproot5#804]
The link https://github.com/scikit-hep/uproot gets forwarded to https://github.com/scikit-hep/uproot3

Is this intentional or should it go to https://github.com/scikit-hep/uproot5 now?

**Comment by jpivarski** [comment]
Unfortunately, we can't change it because `scikit-hep/uproot` was the original repo name. The issue and PR numbers of `scikit-hep/uproot3` and `scikit-hep/uproot5` overlap, so if we changed `scikit-hep/uproot` to point to `scikit-hep/uproot5`, then an old URL for old Uproot issue number 123 would end up pointing to new Uproot issue number 123, which would be wrong.

Those old issue (and PR) numbers probably don't matter much and Google/Bing/whatever's indexing would catch up, but it's best to not make changes to global namespaces. (The changes we made to `uproot`, `uproot3`, `uproot4` names in PyPI, another global namespace, caused troubles that I hadn't foreseen, so I'm erring on the side of being conservative now.)
