### ISSUE TITLE
Incorrect type determined for vector<vector<T>> branches in TTree.arrays()

### ISSUE THREAD

**Issue by TJKhoo** [scikit-hep/uproot5#816]
When generating arrays from multiple branches with different `vector<vector<T>>` types in uproot5, it seems that the type of the first such branch is inadvertently retained for any subsequent ones, causing them to be read incorrectly.

E.g. reading `vector<vector<int32>>` first causes subsequent `vector<vector<float32>>` branches to be read as int (and similar incorrect behaviour if the ordering is changed). This also seems to corrupt the type of that branch permanently, so that e.g. calling `tree['branchname'].array()` breaks in the AwkwardForth generation. The output is detailed together with a demonstrator below. If instead the branches are made into arrays individually, the correct type determination occurs when later calling `arrays()` on the same branches.

Expected behaviour: The type of each branch should be determined independently during execution of `TTree.arrays()`, equivalent to something like:
```
ak.zip({bname:tree[bname].array() for bname in branchlist},depth_limit=1)
```
which gets all the types correct.

See a short demonstrator with the offending input file at:
https://cernbox.cern.ch/s/MxDfDFVmYZTMfRf
* Running this produces the output:
```
100 * {offline_akt4_pf_NOSYS_SumPtTrkPt500: var * var * float32, offline_akt4_pf_NOSYS_NumTrkPt1000: var * var * float32, offline_akt4_pf_NOSYS_TrackWidthPt1000: var * var * float32}
100 * var * var * float32
Traceback (most recent call last):
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/interpretation/objects.py", line 232, in basket_array_forth
    context["forth"].vm = awkward.forth.ForthMachine64(
ValueError: in AwkwardForth source code, line 7 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node0-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1969)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/khoo/Work/ATLAS/JVT_retuning/run/vecvec_type_demonstrator.py", line 14, in <module>
    print(t[v].array().type)
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 1818, in array
    _ranges_or_baskets_to_arrays(
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3066, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/interpretation/objects.py", line 139, in basket_array
    output = self.basket_array_forth(
  File "/Users/khoo/anaconda3/envs/JVT/lib/python3.9/site-packages/uproot/interpretation/objects.py", line 236, in basket_array_forth
    raise type(err)(
ValueError: in AwkwardForth source code, line 7 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node0-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1969)

Forth code generated for this data type:

input stream
    input byteoffsets
    input bytestops
    output node0-offsets int64
output node1-offsets int64
output node2-data float32
output node0-offsets int64
output node1-offsets int64
output node2-data float32

    0 node0-offsets <- stack
0 node1-offsets <- stack
0 node0-offsets <- stack
0 node1-offsets <- stack

    0 do
    byteoffsets I-> stack
    stream seek
    6 stream skip
stream !I-> stack
 dup node0-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
stream #!f-> node2-data
loop
6 stream skip
stream !I-> stack
 dup node0-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
stream #!f-> node2-data
loop

    loop
```
* Changing `do_hack = True` instead produces the expected output:
```
100 * var * var * float32
100 * var * var * int32
100 * var * var * float32
100 * {offline_akt4_pf_NOSYS_SumPtTrkPt500: var * var * float32, offline_akt4_pf_NOSYS_NumTrkPt1000: var * var * int32, offline_akt4_pf_NOSYS_TrackWidthPt1000: var * var * float32}
100 * var * var * float32
100 * var * var * int32
100 * var * var * float32
```

**Comment by GaganMeshram123** [comment]
Hii mentors, I would like to contribute  on your project .
can you please sugest some resources  that can help me solve this problem .

**Comment by jpivarski** [comment]
Hi, @GaganMeshram123! We'd be glad to have help. Also, thanks, @TJKhoo, for reporting this bug.

The current state of things is that I've been unable to give Uproot as much attention as it deserves (to fix bugs like the above), but @ioanaif is getting up to speed on the codebase and is looking at a few issues, including this one, to figure out how to start contributing. (FYI: @ioanaif developed most of Awkward Array version 2, and is switching to Uproot now that Awkward 2 is done.)

To help @ioanaif, but it might also help @GaganMeshram123, I've been writing down everything about the ROOT file format and the Uproot codebase here:

https://github.com/scikit-hep/uproot5/wiki/Guide-to-the-codebase

and I'm not done. In particular, the AwkwardForth part, which this issue concerns, is not written at the time of this comment.

I've also pointed @aryan26roy, the author of the AwkwardForth part, to this issue, but he started a new job last week. `:)`

@TJKhoo is absolutely right that the generation of AwkwardForth for one TBranch should not be affecting any other TBranch. The generated AwkwardForth is saved on the TBranch so that it doesn't need to be generated again, but that ought to be per-TBranch—specifically, the AwkwardForth source code and VM are supposed to be attached to the `AsObjects` interpretation, which is tied to the TBranch through its `interpretation` property. There shouldn't be any interference between the `interpretation` of one TBranch and the `interpretation` of another. Even if two TBranches have the same data type, the AwkwardForth should be regenerated because one might be from one file (with one version of a class streamer) and another might be from a different file (with a different version of the class, and hence different Forth code might be needed to deserialize it). Whatever this problem is, it doesn't get deep into the specifics of how AwkwardForth works; it gets into how generated code gets attached to TBranches/their Interpretations.

@GaganMeshram123, if you would like to learn about Uproot by trying to solve problems like this one, I can talk you through getting started. (That's what I'm doing a lot of these days: teaching.) Send me an email (https://github.com/jpivarski) and we can Zoom-chat. But we should be sure that we're not duplicating effort. @ioanaif, are you planning on taking this issue? If so, let us know!

I would rate this one at medium difficulty. It's not a "shallow" bug like a missing `\n` in a print-out or something. The difficulty level would be "high" if you had to understand the Forth code, but I'm sure this bug does not depend on the Forth itself, just the Python objects that it's attached to.

**Comment by ioanaif** [comment]
Hi! I made a note to leave this issue for you guys to look at :)

**Comment by GaganMeshram123** [comment]
yes mentor,  I am intrested to solve this problem.

**Comment by jpivarski** [comment]
Send me an email at `pivarski@princeton.edu` and we'll arrange a time for a conversation on Zoom. We'll need a back-and-forth conversation to help me understand what you know, what information I can give you about the problem, and we can start the first steps toward figuring it out. (It helps to share screen for something like that.) Also, I'd like to know what your longer-term goals are for working in this area, so that I can help you toward them.

**Comment by jpivarski** [comment]
@GaganMeshram123, let me know if you're still interested in working on this. It's okay if you're not, or if you're too busy, or something else is preventing you from getting to it now. I just need to know if someone else (myself, @ioanaif, ...) should plan to take this issue instead. If now is a bad time, I can help you get started on another issue in a few weeks or so when you do have time. (There will _always_ be more issues!)

**Comment by TJKhoo** [comment]
BTW, @jpivarski, thought it might be worth mentioning that `uproot.iterate` doesn't run into the issue described here, just in case that helps narrow things down.

**Comment by TJKhoo** [comment]
Oh no, I was wrong above :( On closer inspection, exactly the same thing happens with iterate. Sorry for the red herring.
