### ISSUE TITLE
Class-dependent segmentation violation when converting PyROOT objects

### ISSUE THREAD

**Issue by mramospe** [scikit-hep/uproot5#897]
The function `uproot.from_pyroot` crashes for `TProfile3D` objects if the `uproot` package is not loaded in the main scope. As can be tested with the code snippet below, the execution produces a segmentation fault if `import uproot` remains commented. Surprisingly the code runs fine for `TH1D` objects for which it doesn't matter where the package is being imported. The code was tested with `uproot` version `5.0.7`.

```python
import ROOT

# import uproot # if we import uproot at this level then we can use TProfile3D

def function():

    f = ROOT.TFile.Open('test.root', 'recreate')
    # h = ROOT.TH1D() # if we use a TH1D object instead of TProfile3D everything runs fine in both cases
    h = ROOT.TProfile3D()
    h.Write('h')
    f.Close()

    f = ROOT.TFile.Open('test.root', 'read')
    h = f.Get('h')

    import uproot # this import must be defined in the main scope for TProfile3D
    uproot.from_pyroot(h)


function()
```

The execution produces a long backtrace, which finishes with

```
message.WriteObject(obj)
cppyy.ll.SegmentationViolation: void TBufferIO::WriteObject(const TObject* obj, bool cacheReuse = kTRUE) =>
SegmentationViolation: segfault in C++; program state was reset
```

**Comment by franciscosili** [comment]
Same exact problem! Thanks for noting that importing it in the main scope solves the issue!

**Comment by jpivarski** [comment]
This is an interesting puzzle! I can provide some information about what it's doing, though I'm glad that you found a workaround.

`uproot.from_pyroot` and `uproot.to_pyroot` were implemented ([here](https://github.com/scikit-hep/uproot5/blob/main/src/uproot/pyroot.py)) as side-features, taking advantage of the fact that Uproot can deserialize most ROOT objects (`from_pyroot`) and serialize a few types of ROOT objects (`to_pyroot`). Instead of reading and writing to disk, we read from and write to a [TMessage](https://root.cern/doc/master/classTMessage.html), which comes from or is sent to ROOT via PyROOT. If Uproot does not recognize the class (`from_pyroot` only, and shouldn't apply to recent versions of `TProfile3D`), then we also get the [TStreamerInfo](https://root.cern.ch/doc/master/classTStreamerInfo.html) through a [TMemFile](https://root.cern.ch/doc/master/classTMemFile.html), which models an entire file in memory, rather than just a single object, so that we can decode the streamers and learn how to deserialize that class.

I don't see what any of this has to do with importing early or importing late. Perhaps there's some danger in the fact that we use ROOT to compile some C++ code to do some things we can't do on the Python side (defining a subclass of TMessage [here](https://github.com/scikit-hep/uproot5/blob/a8644df7a96ee2d788adb1e35f326ba160bedf48/src/uproot/pyroot.py#L45-L52) and using it to reallocate the TMessage [here](https://github.com/scikit-hep/uproot5/blob/a8644df7a96ee2d788adb1e35f326ba160bedf48/src/uproot/pyroot.py#L92-L119)). Those class definitions are compiled exactly once, protected by module-level Python variables that indicate whether we're in the pre-compilation state or the post-compilation state.

When Python imports a module in a restricted scope (like `function`), access to the names go out of scope, but the module definitions continue to exist; they are not deallocated. It won't forget that it's already compiled these C++ functions, for instance.

I don't see anything, but I'll keep thinking about it in the back of my mind.

**Comment by jpivarski** [comment]
Oh yeah! That's right! It exists in `sys.modules`, but these `TPython::Eval` are being called in some Python scope (in ROOT.py?), and the Uproot global variable is not in that scope. It makes me wonder now why this ever worked, since I would have thought that the `TPython::Eval` scope would be some private-ROOT thing. But maybe not. Anyway, this should be an easy fix, and I'll try it. Thanks!
