### ISSUE TITLE
Can't open files with long file names

### ISSUE THREAD

**Issue by BenGalewsky** [scikit-hep/uproot5#920]
Uproot Version: 5.0.10

I have a very long filename:
```
filename = "/servicey/output/7242feb5-db50-46b3-a3f7-9588c2a204ac/scratch/root:::atlasxrootd-kit.gridka.de:1094::pnfs:gridka.de:atlas:disk-only:atlasdatadisk:rucio:mc16_13TeV:05:ce:DAOD_PHYS.30899209._000097.pool.root.1"
```

When I attempt to open the file with
```python
uproot.open(filenme)
```

It can't open the file and it looks like someone is truncating the name:
```
FileNotFoundError: [Errno 2] No such file or directory: '/servicey/output/7242feb5-db50-46b3-a3f7-9588c2a204ac/scratch/root:::atlasxrootd-kit.gridka.de:1094::pnfs:gridka.de:atlas:disk-only:atlasdatadisk:rucio:mc16_13TeV:05:ce'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/usr/local/lib/python3.10/site-packages/uproot/reading.py", line 581, in __init__
    self._source = Source(
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 108, in __init__
    self._open()
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 118, in _open
    self._fallback = uproot.source.file.MultithreadedFileSource(
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 250, in __init__
    self._open()
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 254, in _open
    [FileResource(self._file_path) for x in range(self._num_workers)]
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 254, in <listcomp>
    [FileResource(self._file_path) for x in range(self._num_workers)]
  File "/usr/local/lib/python3.10/site-packages/uproot/source/file.py", line 38, in __init__
    raise uproot._util._file_not_found(file_path) from err
FileNotFoundError: file not found
```

Note that the error message is showing the filename truncated to 168 characters.

For sanity checking purposes, I tried using python's open function:
```python
open(filename)
<_io.TextIOWrapper name='/servicey/output/7242feb5-db50-46b3-a3f7-9588c2a204ac/scratch/root:::atlasxrootd-kit.gridka.de:1094::pnfs:gridka.de:atlas:disk-only:atlasdatadisk:rucio:mc16_13TeV:05:ce:DAOD_PHYS.30899209._000097.pool.root.1' mode='r' encoding='UTF-8'>
```

Is there an arbitrary limit on the filename? Can it be longer?

## Update
Oddly enough, this works if the argument is a `Path` instance instead of a string

```python
p = Path(filename)
uproot.open(p)
<ReadOnlyDirectory '/' at 0x7f6efcea5660>
```

**Comment by jpivarski** [comment]
I think it's not the length of the filename, but the fact that it has colons in it. If so, we can add this issue to https://github.com/CoffeaTeam/coffea/pull/771#issue-1616039711...

  * https://github.com/scikit-hep/uproot5/issues/47
  * https://github.com/scikit-hep/uproot5/issues/79
  * https://github.com/scikit-hep/uproot5/pull/80
  * https://github.com/scikit-hep/uproot5/pull/81
  * https://github.com/scikit-hep/uproot5/issues/129
  * https://github.com/scikit-hep/uproot5/discussions/365
  * https://github.com/scikit-hep/uproot5/discussions/541
  * https://github.com/scikit-hep/uproot5/discussions/543
  * https://github.com/scikit-hep/uproot5/issues/669
  * https://github.com/scikit-hep/uproot5/pull/670

If this is it, there are two workarounds (either one works):

  1. Make the filename a `pathlib.Path`, rather than a `str`.
  2. Replace filename string `x` with dict `{x: None}`. This one works because the colon is splitting between the filesystem-path and the object-inside-ROOT-file-path, and the dict syntax is another way of doing that split, with `None` for no object-inside-ROOT-file-path.

I wish, I wish, I wish I could remove this colon feature, but when it was absent in Uproot 4.0 (because 4.0 was allowed to make backward-breaking changes from 3.x), users missed it (and thought that Uproot 4.0 was incapable of reading files that were readable in 3.x). In my [investigations into API usage](https://indico.jlab.org/event/459/contributions/11547/), I found that it's not an uncommonly used feature; people would still miss it if it disappears again.
