### ISSUE TITLE
Reading the RNtuple PHYSLITE prototype

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/uproot5#975]
We are starting to have RNtuple prototypes for PHYSLITE. This is all in a very early stage, so things might change. However i still wanted to start looking how we can read them from uproot in parallel to the developments.

Here is a small example file, produced with [produce_rntuple.sh](https://github.com/nikoladze/physlite_experiments/blob/9ce36623d5cd21b6ff748a0231f63fb4d882b397/physlite_experiments/scripts/produce_rntuple.sh):
[DAOD_PHYSLITE_2023-09-13T1230.art.rntuple.root.zip](https://github.com/scikit-hep/uproot5/files/12819286/DAOD_PHYSLITE_2023-09-13T1230.art.rntuple.root.zip)

First, i run into #974, since the RNtuple in that file is under the key `"RNT:CollectionTree"` which has a colon in the name. But when i work around this i can at least read the RNtuple object:

```python
import uproot
rnt = uproot.open({"DAOD_PHYSLITE_2023-09-13T1230.art.rntuple.root": "RNT:CollectionTree"})
```

`rnt.field_names` and `rnt.column_records` seem to work as well, but when i try to read data i get an Exception, e.g.

<details>

```python
In [2]: rnt.arrays(["AnalysisJetsAux::pt"])
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 rnt.arrays(["AnalysisJetsAux::pt"])

File ~/code/uproot/src/uproot/models/RNTuple.py:392, in Model_ROOT_3a3a_Experimental_3a3a_RNTuple.arrays(self, filter_names, filter_typenames, entry_start, entry_stop, decompression_executor,
 array_cache)
    381 def arrays(
    382     self,
    383     filter_names="*",
   (...)
    388     array_cache=None,
    389 ):
    390     ak = uproot.extras.awkward()
--> 392     entry_stop = entry_stop or self._length
    394     clusters = self.cluster_summaries
    395     cluster_starts = numpy.array([c.num_first_entry for c in clusters])

File ~/code/uproot/src/uproot/models/RNTuple.py:178, in Model_ROOT_3a3a_Experimental_3a3a_RNTuple._length(self)
    176 @property
    177 def _length(self):
--> 178     return sum(x.num_entries for x in self.cluster_summaries)

File ~/code/uproot/src/uproot/models/RNTuple.py:173, in Model_ROOT_3a3a_Experimental_3a3a_RNTuple.cluster_summaries(self)
    171 @property
    172 def cluster_summaries(self):
--> 173     return self.footer.cluster_summaries

File ~/code/uproot/src/uproot/models/RNTuple.py:162, in Model_ROOT_3a3a_Experimental_3a3a_RNTuple.footer(self)
    159 cursor = self._footer_cursor.copy()
    160 context = {}
--> 162 f = FooterReader().read(self._footer_chunk, cursor, context)
    163 assert (
    164     f.header_crc32 == self.header.crc32
    165 ), f"crc32={self.header.crc32}, header_crc32={f.header_crc32}"
    166 assert f.crc32 == zlib.crc32(self._footer_chunk.raw_data[:-4])

File ~/code/uproot/src/uproot/models/RNTuple.py:695, in FooterReader.read(self, chunk, cursor, context)
    692 out.feature_flag = cursor.field(chunk, _rntuple_feature_flag_format, context)
    693 out.header_crc32 = cursor.field(chunk, struct.Struct("<I"), context)
--> 695 out.extension_links = self.extension_header_links.read(chunk, cursor, context)
    696 out.col_group_records = self.column_group_record_frames.read(
    697     chunk, cursor, context
    698 )
    699 out.cluster_summaries = self.cluster_summary_frames.read(chunk, cursor, context)

File ~/code/uproot/src/uproot/models/RNTuple.py:554, in ListFrameReader.read(self, chunk, cursor, context)
    550 local_cursor = cursor.copy()
    551 num_bytes, num_items = local_cursor.fields(
    552     chunk, _rntuple_frame_header, context
    553 )
--> 554 assert num_bytes < 0, f"num_bytes={num_bytes}"
    555 cursor.skip(-num_bytes)
    556 return [
    557     self.payload.read(chunk, local_cursor, context) for _ in range(num_items)
    558 ]

AssertionError: num_bytes=37077
```

</details>

The exception seems to occur when reading the footer, so maybe it's the same issue as reported in #928, let's see.

For Information: also in ROOT this is currently bleeding edge and to read that file one needs features currently not in a release yet. But it works with a nightly version of root, e.g

<details>

```
# setup in centos7 environment
source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-opt/setup.sh
```

```python
import ROOT
rnt = ROOT.Experimental.RNTupleReader.Open("RNT:CollectionTree", "DAOD_PHYSLITE_2023-09-13T1230.art.rntuple.root")
view = rnt.GetView[ROOT.std.vector[ROOT.float]]("AnalysisJetsAux::pt")

>>> view(0)
vector<float>{ 155946.f, 140229.f, 120520.f, 119895.f, 69683.3f, 28485.4f, 18776.9f, 10522.2f, 11948.9f }
```

(To read all branches, e.g. also those involving custom classes one needs to setup Athena)

</details>

**Comment by nikoladze** [comment]
tagging @Moelf

**Comment by jpivarski** [comment]
@ioanaif, @agoose77, and I were talking about it this morning. First thing: Uproot needs to be able to address names with colons in them—I don't know how I thought that `:` between a TTree and its TBranches was a good idea. (You're also allowed to use `/` in that context, even though the nesting of TBranches within TBranches within a TTree is not the same as the nesting of TDirectories within TDirectories, at least that couldn't conflict with valid names.)

Colons in names is valid in ROOT:

```python
% python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> f = ROOT.TFile("/tmp/whatever.root", "RECREATE")
>>> h = ROOT.TH1D("has:colon", "", 5, 0, 1)
>>> h.Write()
249
>>> f.Close()
>>> 
% python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> f = ROOT.TFile("/tmp/whatever.root")
>>> h = f.Get("has:colon")
>>> h
<cppyy.gbl.TH1D object at 0x55aafcee03c0>
```

So Uproot needs to be able to read and write them.

We can't just change [uproot.ReadOnlyDirectory](https://uproot.readthedocs.io/en/latest/uproot.reading.ReadOnlyDirectory.html)'s and [uproot.WritableDirectory](https://uproot.readthedocs.io/en/latest/uproot.writing.writable.WritableDirectory.html)'s `__getitem__` and `__setitem__` methods, and we can't introduce a function argument because they're square brackets, not function calls with arguments. Assignment can't have a function call on the left-hand-side because of Python syntax.

[uproot.ReadOnlyDirectory](https://uproot.readthedocs.io/en/latest/uproot.reading.ReadOnlyDirectory.html) has a more low-level `get` method (which is oddly not in the documentation). That function does nested directories with `/` and `:` parsing, though it could take a new argument to prevent this.

As an ugly solution that experts would need to be "in the know" to use, we could add an argument preventing `/` and `:` parsing to `__getitem__` and `__setitem__` themselves, so users would have to literally call `__getitem__` and `__setitem__` by name instead of using square brackets and assignment.

As a less-ugly solution, we could add a proxy like Awkward's [ak.mask](https://awkward-array.org/doc/main/reference/generated/ak.mask.html) (see "Another syntax" at the end of the page). It would be implemented a bit like this:

```python
class WritableDirectory:
  @property
  def noparse(self):
    return ReadOnlyDirectory._NoParse(self)
  class _NoParse:
    def __init__(self, directory):
      self._directory = directory
    def __getitem__(self, where):
      pass  # get an item without parsing directories
    def __setitem__(self, where, what):
      pass  # set an item without parsing directories
```

but with a better name than `noparse`. That would allow

```python
>>> directory.noparse["has:column"]
>>> directory.noparse["has:column"] = "blub"
```

Thoughts?

**Comment by agoose77** [comment]
@jpivarski how do you feel about the `__getitem__` treating keys as higher precedence over "paths"? e.g.
```python

def parse_first(keys, where, allow_colon=True):
    longest_keys = sorted(keys, key=len, reverse=True)

    for key in longest_keys:
        # Prefer to match a key vs a pattern
        if where.startswith(key):
            remainder = where[len(key) :]
            if remainder.startswith("/") or (remainder.startswith(":") and allow_colon):
                next_where = remainder[1:]
            else:
                next_where = None
            return key, next_where
    else:
        pattern = ":/" if allow_colon else "/"
        # parse the key
        head_tail = re.split(pattern, where, maxsplit=1)

        # Does the string not contain this pattern?
        if len(head_tail) == 1:
            raise ValueError(f"Encountered non-key {where}")
        else:
            return tuple(head_tail)


assert parse_first({"bla:bla"}, "bla:bla") == ('bla:bla', None)
assert parse_first({"bla"}, "bla/bla") == ('bla', "bla")
assert parse_first({"bla"}, "bla:bla") == ('bla', "bla")
assert parse_first({"bla:bla", "bla"}, "bla:bla") == ('bla:bla', None)
```

**Comment by Moelf** [comment]
ok yeah PHYSLITE is wild but I think it's kinda just working out of the box! https://gist.github.com/Moelf/63308270b7a8143465b39f2d8fa3f98b

but also there are top level columns that look suspecious at first glance:

```julia
├─ :AnalysisJets ⇒ Vector
│                  ├─ :offset ⇒ Leaf{UnROOT.Index64}(col=181)
│                  └─ :content ⇒ Struct
│                                └─ Symbol(":_0") ⇒ Struct
│                                                   └─ Symbol(":_0") ⇒ Struct
│                                                                      └─ Symbol(":_0") ⇒ Struct

julia> df[:, :AnalysisJets]
ERROR: ArgumentError: only eltypes with fields are supported
Stacktrace:
  [1] (StructArrays.StructVector{@NamedTuple{}, @NamedTuple{}})(c::@NamedTuple{})
    @ StructArrays ~/.julia/packages/StructArrays/0h2SD/src/structarray.jl:17
  [2] (StructArrays.StructArray{@NamedTuple{}})(c::@NamedTuple{})
    @ StructArrays ~/.julia/packages/StructArrays/0h2SD/src/structarray.jl:94
```

**Comment by jpivarski** [comment]
> @jpivarski how do you feel about the `__getitem__` treating keys as higher precedence over "paths"?

At first, I thought that's a great idea, but what if a file contains

```
└─ has
    └─ colon
```

(assuming `has` is a TTree and `colon` is a TBranch). At this point in time, someone can access `colon` by `file["has:colon"]`.

Later, another object is added (any type).

```
├─ has
│   └─ colon
└─ has:colon
```

Now the same `file["has:colon"]` would return a different object. How a path gets resolved depends on what other objects exist, a kind of action at a distance.

It's not terrible because the original object is still addressable, as `file["has"]["colon"]`. It's also a corner case that we can recognize and explain if it ever comes up.

This only applies to colons, not slashes. ROOT doesn't allow slashes in names:

```python
% python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> f = ROOT.TFile("/tmp/whatever.root", "RECREATE")
>>> h = ROOT.TH1D("has/slash", "", 5, 0, 1)
>>> h.Write()
249
>>> f.Close()
>>> 
% python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> f = ROOT.TFile("/tmp/whatever.root")
>>> h = f.Get("has/slash")
>>> h
<cppyy.gbl.TH1D object at 0x(nil)>
```

(Note the `0x(nil)`.)

Ah, but there's another problem with the precedence solution: when using it to assign a new object, like

```python
>>> file["new:object"] = whatever
```

should it make an object with that whole name or make a directory named `new` containing an object named `object`?

Ah², it can't: colons are only for TTree-TBranch combinations. `file["new:object"]` can't be a TTree named `new` and a TBranch named `object`; that's not how the interface works. So the above code should always make a new object named `new:object`. And the same thing with `new/object` does not apply: you can never make a ROOT object with a `/` in its name.

So I think this is a good solution, particularly since it doesn't add new features that users are supposed to use instead of the obvious ones. The only subtleties (action at a distance) are rare, can be explained, and can be worked around. I'm in favor of the new precedence rule.

**Comment by jpivarski** [comment]
I'm sorry—I intended all of the discussion about colons to be on #974. I didn't notice that there were two issues. Anything else about colons should go to $974 instead of here.

This issue is about PHYSLITE. The problems reading it ~~may be~~ are likely related to #928. Uproot is not up-to-date on RNTuple reading. (The format changed.)
